"""Download and normalize the public CIST HTML schedule."""

from __future__ import annotations

import argparse
import json
import os
import re
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any
from urllib.parse import quote
from zoneinfo import ZoneInfo

import requests
from bs4 import BeautifulSoup, Tag


BASE_URL = "https://cist.nure.ua/ias/app/tt"
GROUP_NAME = "УК-26-1"
GROUP_ID = 12354277
KYIV = ZoneInfo("Europe/Kyiv")
USER_AGENT = "nure-schedule/1.0 (+https://github.com/; educational project)"
DATE_RE = re.compile(r"^\d{2}\.\d{2}\.\d{4}$")
TIME_RE = re.compile(r"^(\d{2}:\d{2})\s+(\d{2}:\d{2})$")
TYPE_RE = re.compile(r"\b(Лк|Пз|Лб|Конс|Екз|Зал)\b")


class ScheduleError(RuntimeError):
    """Raised when CIST returns data that is unsafe to publish."""


def _decode_cist(response: requests.Response) -> str:
    """CIST declares and serves its legacy pages as Windows-1251."""
    try:
        return response.content.decode("windows-1251")
    except UnicodeDecodeError as exc:
        raise ScheduleError("CIST response is not valid Windows-1251 HTML") from exc


def fetch_schedule(
    first_date: str,
    last_date: str,
    group_id: int = GROUP_ID,
    *,
    timeout: tuple[float, float] = (10, 30),
) -> str:
    """Reproduce CIST's “HTML format” action with a fresh APEX session.

    The first GET asks Oracle APEX to create a session. The session id is read
    from the returned form and used in the page-201 URL generated by CIST's own
    IAS_GROUP_TT_HTML JavaScript function.
    """
    headers = {"User-Agent": USER_AGENT, "Accept": "text/html,application/xhtml+xml"}
    with requests.Session() as client:
        try:
            landing = client.get(
                f"{BASE_URL}/f",
                params={"p": "778:2"},
                headers=headers,
                timeout=timeout,
            )
            landing.raise_for_status()
        except requests.RequestException as exc:
            raise ScheduleError(f"Cannot create CIST APEX session: {exc}") from exc

        landing_html = _decode_cist(landing)
        landing_soup = BeautifulSoup(landing_html, "html.parser")
        instance = landing_soup.select_one('input[name="p_instance"]')
        session_id = instance.get("value", "") if instance else ""
        if not re.fullmatch(r"\d+", str(session_id)):
            raise ScheduleError("CIST did not return a valid APEX session id")

        apex_page = (
            f"778:201:{session_id}:::201:"
            "P201_FIRST_DATE,P201_LAST_DATE,P201_GROUP,P201_POTOK:"
            f"{first_date},{last_date},{group_id},0:"
        )
        # Keep APEX separators readable while escaping unexpected user input.
        schedule_url = f"{BASE_URL}/f?p={quote(apex_page, safe=':,')}"
        try:
            response = client.get(schedule_url, headers=headers, timeout=timeout)
            response.raise_for_status()
        except requests.RequestException as exc:
            raise ScheduleError(f"Cannot download CIST HTML schedule: {exc}") from exc

    html = _decode_cist(response)
    if not BeautifulSoup(html, "html.parser").select_one("table.MainTT"):
        raise ScheduleError("CIST response does not contain table.MainTT")
    return html


def _teacher_names(cell: Tag, lesson_type: str) -> list[str]:
    """Find teachers in the footer segment belonging to one lesson type."""
    teachers: list[str] = []
    active_type: str | None = None
    for node in cell.descendants:
        if isinstance(node, str):
            matches = TYPE_RE.findall(node)
            if matches:
                active_type = matches[-1]
        elif isinstance(node, Tag) and node.name == "a":
            href = node.get("href", "")
            if active_type == lesson_type and "P202_SOTR" in href:
                name = node.get_text(" ", strip=True)
                if name and name not in teachers:
                    teachers.append(name)
    return teachers


def _parse_footer(soup: BeautifulSoup) -> dict[str, dict[str, Any]]:
    subjects: dict[str, dict[str, Any]] = {}
    footer = soup.select_one("table.footer")
    if not footer:
        raise ScheduleError("CIST HTML does not contain the subject footer")

    for row in footer.select("tr"):
        cells = row.find_all("td", recursive=False)
        anchor = cells[0].find("a", attrs={"name": True}) if len(cells) >= 2 else None
        if not anchor:
            continue
        subject_id = str(anchor["name"])
        details = cells[1]
        text = details.get_text(" ", strip=True)
        full_name = text.split(" : ", 1)[0].strip()
        types = {kind: _teacher_names(details, kind) for kind in TYPE_RE.findall(text)}
        subjects[subject_id] = {"subject": full_name, "teachers": types}
    return subjects


def _lesson_from_cell(
    cell: Tag,
    date_value: str,
    start: str,
    end: str,
    footer: dict[str, dict[str, Any]],
) -> dict[str, Any] | None:
    link = cell.select_one("a.linktt[href^='#']")
    if not link:
        return None

    label = link.get_text(" ", strip=True)
    type_match = TYPE_RE.search(label)
    lesson_type = type_match.group(1) if type_match else ""
    subject_id = str(link.get("href", "")).removeprefix("#")
    subject_info = footer.get(subject_id, {})

    # The room follows the subject link as plain text (e.g. DL or DL, DL_1).
    room_text = " ".join(cell.stripped_strings)
    room = room_text.removeprefix(label).strip(" ,")
    return {
        "date": datetime.strptime(date_value, "%d.%m.%Y").date().isoformat(),
        "start": start,
        "end": end,
        "subject": subject_info.get("subject") or TYPE_RE.sub("", label).strip(),
        "type": lesson_type,
        "teachers": subject_info.get("teachers", {}).get(lesson_type, []),
        "room": room,
        "subject_id": int(subject_id) if subject_id.isdigit() else subject_id,
    }


def parse_schedule(html: str) -> list[dict[str, Any]]:
    """Expand CIST's week-grid table into one normalized object per lesson."""
    soup = BeautifulSoup(html, "html.parser")
    table = soup.select_one("table.MainTT")
    if not table:
        raise ScheduleError("CIST HTML does not contain table.MainTT")
    footer = _parse_footer(soup)

    current_dates: list[str] = []
    lessons: list[dict[str, Any]] = []
    for row in table.find_all("tr", recursive=False):
        cells = row.find_all("td", recursive=False)
        date_cells = [cell.get_text(" ", strip=True) for cell in cells if "date" in cell.get("class", [])]
        dated = [value for value in date_cells if DATE_RE.fullmatch(value)]
        if dated:
            current_dates = dated
            continue
        if len(cells) < 3 or not current_dates:
            continue

        time_match = TIME_RE.fullmatch(cells[1].get_text(" ", strip=True))
        if not time_match:
            continue
        start, end = time_match.groups()
        week_index = 0
        for cell in cells[2:]:
            span = int(cell.get("colspan", 1))
            for date_value in current_dates[week_index : week_index + span]:
                lesson = _lesson_from_cell(cell, date_value, start, end, footer)
                if lesson:
                    lessons.append(lesson)
            week_index += span

        if week_index != len(current_dates):
            raise ScheduleError("CIST week grid has an unexpected colspan structure")

    lessons.sort(key=lambda item: (item["date"], item["start"], str(item["subject_id"])))
    return lessons


def validate_schedule(data: dict[str, Any]) -> None:
    lessons = data.get("lessons")
    if data.get("group_id") != GROUP_ID or data.get("group") != GROUP_NAME:
        raise ScheduleError("Parsed schedule belongs to an unexpected group")
    if not isinstance(lessons, list) or not lessons:
        raise ScheduleError("Parsed schedule is unexpectedly empty")
    required = {"date", "start", "end", "subject", "type", "teachers", "room"}
    for index, lesson in enumerate(lessons):
        if not required.issubset(lesson) or not lesson["subject"]:
            raise ScheduleError(f"Lesson {index} is missing required fields")
        datetime.fromisoformat(lesson["date"])
        if not re.fullmatch(r"\d{2}:\d{2}", lesson["start"]):
            raise ScheduleError(f"Lesson {index} has an invalid start time")


def build_schedule(html: str) -> dict[str, Any]:
    data = {
        "group": GROUP_NAME,
        "group_id": GROUP_ID,
        "updated_at": datetime.now(KYIV).isoformat(timespec="seconds"),
        "source": "CIST",
        "timezone": "Europe/Kyiv",
        "lessons": parse_schedule(html),
    }
    validate_schedule(data)
    return data


def write_if_changed(data: dict[str, Any], destination: Path) -> bool:
    """Atomically replace JSON only when actual schedule content changed."""
    if destination.exists():
        try:
            previous = json.loads(destination.read_text(encoding="utf-8"))
            comparable = {key: value for key, value in data.items() if key != "updated_at"}
            old_comparable = {key: value for key, value in previous.items() if key != "updated_at"}
            if comparable == old_comparable:
                return False
        except (OSError, json.JSONDecodeError):
            pass

    destination.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
    fd, temp_name = tempfile.mkstemp(prefix="schedule-", suffix=".tmp", dir=destination.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as temp_file:
            temp_file.write(payload)
            temp_file.flush()
            os.fsync(temp_file.fileno())
        os.replace(temp_name, destination)
    except Exception:
        Path(temp_name).unlink(missing_ok=True)
        raise
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--first-date", default="01.09.2026", help="CIST date, DD.MM.YYYY")
    parser.add_argument("--last-date", default="31.01.2027", help="CIST date, DD.MM.YYYY")
    parser.add_argument("--input-html", type=Path, help="Parse a saved fixture instead of CIST")
    parser.add_argument("--output", type=Path, default=Path("data/schedule.json"))
    args = parser.parse_args()

    if args.input_html:
        html = args.input_html.read_bytes().decode("windows-1251")
    else:
        html = fetch_schedule(args.first_date, args.last_date)
    changed = write_if_changed(build_schedule(html), args.output)
    print("Schedule updated." if changed else "Schedule has not changed.")


if __name__ == "__main__":
    main()
